load("synchronization_series.RData")
library(rEDM)
total_network_distances <- as.numeric(unlist(total_network_distances))
difference <- diff(total_network_distances)
#simplex( total_network_distances )
simplex( difference )
